# Generated by Django 2.2 on 2019-09-11 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 16, 17, 3, 913956, tzinfo=utc)),
        ),
    ]
